### ISSUE TITLE
After Skip Intro button auto-click, play button auto-click doesn't always resume video playback

### ISSUE THREAD

**Issue by Fprince333** [jonluca/Never-Ending-Netflix#4]
I noticed this after your update, which works well for the first several episodes. The issue appears after the code ensures the [play button gets clicked](https://github.com/jonluca/Never-Ending-Netflix/blob/fd56600692c891967125bd5cf6dd781481bab0ef/NEN.js#L42). 

The video will be paused even though the play button has been auto-clicked. The paused button even appears on the screen so you can tell the code worked. Maybe there should be a check on the status of the video playback as well?

**Comment by jonluca** [comment]
Is the code itself pausing the video? Or is it just not fixing the original bug of it weirdly pausing after skipping the intro?

I'm not sure why this is happening - the code is fairly simple, and it's just calling `.click()` on the "Skip Intro" DOM node. 

Maybe we could put it in a timeout? The only thing I can think of is a race condition here - we're using the mutation observer to see when it's been inserted, and maybe our code runs before some other handling code from Netflix?

**Comment by Fprince333** [comment]
From what I can tell, it seems to be a Netflix UI bug where the clicking the play button does everything it's supposed to do other than resume playing the video. I noticed this yesterday occasionally getting to this state but thought it was due to my debugging in the console. So it doesn't seem that this code here is the cause of this behavior. 

You might be right, it's hard to say for sure about it being a race condition. Strange that it works for the first few episodes and only after viewing for a while does this occur. I haven't experienced the randomness that might come from race condition issues.

**Comment by Fprince333** [comment]
Seems like Netflix figured their stuff out - this no longer seems to be an issue.

**Comment by mikeyaworski** [comment]
I'm actually still having this issue. I ran the extension locally and increased the delay up from 150 on pressing Play after skipping. I found anything over 250 solved the problem for me. 200 was still too small of a delay.

https://github.com/jonluca/Never-Ending-Netflix/blob/6b71673af2b0d3f6bc52ebc440ea4464efee25ea/NEN.js#L48

Unfortunately this workaround makes an awkward stutter with the pause/play after the intro even if the timing is right. Not sure if there's an alternative, but for now, the delay should be increased or should be attempted several times.

**Comment by jonluca** [comment]
That's unfortunate. Yeah, that stutter and skip is pretty horrendous. We can try an exponential backoff with 5 or 10 max tries? It's still a bad experience. 

I'd like to get to the root cause. Maybe if we wait for half a second before clicking skip intro?

**Comment by jonluca** [comment]
Ok I just made another change - I *think* this should prevent the pause button. I 1) Wait 200ms before clicking just the Skip Intro button and 2) make sure that we haven't clicked skip intro in the last 1000ms.

I believe this should be identical to just pressing it - we shouldn't run into pauses anymore. I'll keep this issue open in case other people have this problem, and close it in 2 weeks otherwise.

**Comment by mikeyaworski** [comment]
Was this tested and worked on your local machine? Because for me, it doesn't skip the intro anymore and keeps pressing play after I pause it during the intro.

**Comment by jonluca** [comment]
What version of the extension are you on? There was a small bug that I thought I fixed

**Comment by mikeyaworski** [comment]
2.2.2

**Comment by jonluca** [comment]
Dang, yeah that's the most up to date.

Are there any stack traces in the console? 

I also just pushed a commit to the repo. Could you try loading the extension in dev mode with the newest commit (Load Unpacked Extension from the Chrome Extensions page) and let me know if it's still happening?

**Comment by jonluca** [comment]
Also what show is this happening on?

**Comment by mikeyaworski** [comment]
I cloned from the latest commit and it now lets me pause during the intro, but still doesn't skip the intro. This console error happens several times during the intro:

```
70165209:1 Uncaught TypeError: Illegal invocation
setTimeout (async)
_ @ NEN.js:41
childList (async)
jn @ none:3
hr @ none:4
mr @ none:3
dr @ none:3
cr @ none:3
nr @ none:3
enqueueSetState @ none:4
u.setState @ none:2
onIdle @ none:6
setTimeout (async)
enterInactiveUIState @ none:6
onInactive @ none:6
setTimeout (async)
onUserActivityChanged @ none:6
onUserActivityChanged @ none:6
onMouseLeave @ none:6
i @ none:2
a @ none:2
o @ none:2
s @ none:2
p @ none:2
h @ none:2
d @ none:2
g @ none:2
Re @ none:2
yr @ none:4
$ @ none:2
Ve @ none:2
```

And the show is That '70s Show, specifically episodes S1E11-13 where I test it

**Comment by jonluca** [comment]
Ok great, I think it was my shorthand. 

I went from `setTimeout(elem.click, 100)` to `setTimeout(_ =>{ elem.click()}, 100)`. Not sure why it would make a difference, but I *think* that fixed it.

Thanks so much!

**Comment by jonluca** [comment]
Ok I pushed v2.2.3. Hopefully this one fixes it.

Thanks for the help!

**Comment by mikeyaworski** [comment]
Yup, that solved the problem for me. It auto skips and doesn't pause after the intro anymore. Awesome

**Comment by farosch** [comment]
@jonluca Seems like this is a problem again in v2.3.1.
Same behaviour as described before: The intro is being skipped but the video playback isn't resumed after that. Happens to me all of the time. Not sure how to debug it though..
